# 应用服务 WEB 访问端口
server:
  port: 8081

spring:
  main:
    lazy-initialization: false # 全局禁用懒加载（谨慎！可能增加启动时间）
  application:
    name: springcloud-consumer
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP
      - optional:nacos:common-postgrepsql.yaml?group=DEFAULT_GROUP
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      httpclient:
        enabled: true
        max-connections: 200
        max-connections-per-route: 50
        connection-timeout: 2000
    loadbalancer:
      enabled: true
      eager-load:
        clients: springcloud-provider
    nacos:
      discovery:
        server-addr: 192.168.184.135:8848
      config:
        server-addr: 192.168.184.135:8848
        file-extension: yaml
dubbo:
  application:
    name: springcloud-consumer
    qos-port: 22222
