# 应用服务 WEB 访问端口
server:
  port: 8083

spring:
  main:
    lazy-initialization: false # 全局禁用懒加载（谨慎！可能增加启动时间）
  data:
    redis:
      host: localhost
      port: 6379

  application:
    name: springcloud-user